import differentiable_structures_differential_topology_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace differentiable_structures_differential_topology_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end differentiable_structures_differential_topology_theorem_canonical_lane_mathlib
end HautevilleHouse
